### ISSUE TITLE
Non funziona su Linux

### ISSUE THREAD

**Issue by gmstyle** [nightflyer73/plugin.video.sportube#2]
Ciao volevo segnalare che l'add-on non funziona su Linux, per l'esatezza Ubuntu 14.04 con Kodi 15.2.
Non si avvia e compare il messaggio classico di controllare il file di log.
Grazie

**Comment by nightflyer73** [comment]
Condividi il file di log. Grazie.

**Comment by gmstyle** [comment]
Non sono riuscito a trovarlo su Linux.  Dove dovrebbe stare?  Grazie

**Comment by nightflyer73** [comment]
Qui:
http://kodi.wiki/view/Log_file/Advanced#Location

Comunque non è più necessario. Ho riprodotto l'errore che è dovuto al fatto che il sito ha cambiato nuovamente API.

**Comment by nightflyer73** [comment]
Mmmm.... però l'ultima versione sul repository Kodi non è l'ultima presente in questo repository... molto strano.

**Comment by gmstyle** [comment]
Quindi mi consigli di scaricare l'ultima versione dal reportage github oppure risolvi e poi avvisi?

**Comment by gmstyle** [comment]
Repository

**Comment by nightflyer73** [comment]
Duplicate of #3
