### ISSUE TITLE
'int' object is unsubscriptable

### ISSUE THREAD

**Issue by nicoursi** [nightflyer73/plugin.video.sportube#3]
Hello,
If there are no live events, no problems. I just get an empty list. 
If there are live events, the the script just crashes.

You can find a logcat here:
http://goo.gl/hSSjXK (1 month expiration)

Thank you for your commitment!
Nicola

**Comment by nightflyer73** [comment]
To solve this issue replace the following line in default.py:
title = live[1] + " - " + live[12] + " (" + live[11][11:] + ")"

In this way:
title = live[1] + " - " + live[13] + " (" + live[12][11:16] + ")"

Please let me know it if fixes the problem for you.

**Comment by nicoursi** [comment]
Yes it did fix the problem! Thank you very much!!

**Comment by nicoursi** [comment]
I can now play but after a couple of minutes CPU-KODI usage jumps to 130% and the streaming becomes unwatchable.

To make sure there was no interference from other plugins I installed sportube on a fresh kodi installation and the problem persists.

[kodi.log.zip](https://github.com/nightflyer73/plugin.video.sportube/files/104872/kodi.log.zip)

Grazie ancora per la disponibilità! Se preferisci scrivo in italiano, a meno che non voglia tenere il progetto internazionale :)

**Comment by nightflyer73** [comment]
This problem is not plugin related. Streams are directly handled by Kodi.

**Comment by nicoursi** [comment]
I can understand this, but I use Stream on Demand,  genesis and sportsdevil with no problem. cpu usage stays stable and i can watch awhole event/movie with no problem.
I run sportube on three different platforms (windows 10, linux mint 17.3 and Android 4.4.2) and I have the same problem on all of them. 

How can it be just kodi related? If it was kodi related I shouldn't be able to stream with any other addon. I have problems only with this addon and on three different devices with the same exact symptom...

If you are 100% sureith's not addon related, would it be possible for you to adrress me to the real source, as I am not an expert on these sort of things?

thank you  for your time!

**Comment by nightflyer73** [comment]
The plugin job ends when the stream starts. Therefore, yes, I'm 100% sure it's not an addon problem. Streams can greatly vary, having different formats, different bit rates, etc. Hence the fact that you can play some streams in some addons is not a guarantee for anything. Try to lower the maximum stream bit rate in Kodi settings and see if you have a different behaviour.

**Comment by nicoursi** [comment]
Thank you for clarifying. Adjusting the bitrate didn't work, also because kodi offers only an automatic feature for this, I can't lower or increase.

I tried to play with hardware acceleration too, with no results. The very strange thing is that today is working acceptably well, it just blocks sometimes and most of the time it resumes automatically. I really don't know what to think. Maybe it could even be bandwidth related, as where I live we have good bandwidth only during the night and morning up to noon. 

As this isn't related to this addon i'll try discuss this issue on the kodi forum.

Thanks again
