### ISSUE TITLE
Probabile cambio API - vedi log

### ISSUE THREAD

**Issue by nicoursi** [nightflyer73/plugin.video.sportube#4]
Il plugin va in crash.
[kodi.log.zip](https://github.com/nightflyer73/plugin.video.sportube/files/149341/kodi.log.zip)

**Comment by gmstyle** [comment]
idem x me. ecco il log

14:46:20 T:2808265536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: coercing to Unicode: need string or buffer, int found
                                            Traceback (most recent call last):
                                              File "/home/gmstyle/.kodi/addons/plugin.video.sportube/default.py", line 73, in <module>
                                                show_root_menu()
                                              File "/home/gmstyle/.kodi/addons/plugin.video.sportube/default.py", line 67, in show_root_menu
                                                title = live[1] + " - " + live[13] + " (" + live[12][11:16] + ")"
                                            TypeError: coercing to Unicode: need string or buffer, int found
                                            -->End of Python script error report<--
14:46:20 T:3033163648   ERROR: GetDirectory - Error getting plugin://plugin.video.sportube/
14:46:20 T:3033163648   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.sportube/) failed

**Comment by nightflyer73** [comment]
I have a new version that works with the new API. I will commit it ASAP. Please, be patient. Anyway I'm a bit tired of these frequent changes (once a month!). I might stop developing this addon if this situation doesn't change.
