### ISSUE TITLE
Login required

### ISSUE THREAD

**Issue by padremayi** [nightflyer73/plugin.video.sportube#6]
I receive an error when I start the Add-on on Kodi.

Now the site requires login in order to watch a live match

**Comment by eugenio412** [comment]
Yes, seems like the link field is empty if you are not logger and/or you didn't buy the match, I asked sportube some documentation, let's see if they reply.
The whole script is working, but it needs a login.

**Comment by padremayi** [comment]
I have an account but not the possibility to insert the credentials

**Comment by eugenio412** [comment]
Sportube is not replying at all, you can try too, but no answer here. Seems like they are not interested in having a decent API, or developers working at it

**Comment by eugenio412** [comment]
Now I have a new working forked version done by me, enjoy
[https://github.com/eugenio412/plugin.video.sportube](url)

**Comment by nightflyer73** [comment]
Happy to hear there is a new fork. 

I'll close this issue because this addon is no longer maintained.
