### ISSUE TITLE
pythonToCppException

### ISSUE THREAD

**Issue by allegfede** [nightflyer73/plugin.video.sportube#9]
baseUrl=match[0]
IndexError: list index out of range
-----

is there a more updated plug in version?

**Comment by nightflyer73** [comment]
This plugin is no longer maintained.
https://github.com/nightflyer73/plugin.video.sportube/commit/9858c0409d0e10cc6c040e84c055a72ea22c8e7c

**Comment by allegfede** [comment]
and is there an alternative (if you know) to view (legally acquired) eleven sport (sport.tv) events?

thanks a lot
